### ISSUE TITLE
Renaming a theme through the QGIS interface should update the selected theme in the plugin interface

### ISSUE THREAD

**Issue by bkepl** [mach0/themeselector#12] opened 2023-07-01 01:34 UTC
Besides this behavior, if the plugin interface is open when renaming the theme through the QGIS interface, subsequent attempts to rename a theme through the plugin interface fail and the Rename dialog reappears. If clicked again to "Rename," the theme is deleted.

**Comment by mach0** [comment] 2024-11-27 21:13
Duplicate of #7

**Closed** 2024-11-27 21:13 UTC
